# Python Primer

## D.1 Getting Started

In [1]:
print("Hello World!")

Hello World!


Python strings can be formatted using the **format** function. The bracket syntax `{i}` provides a dplace holder for the i-th variable to be printed, with 0 being the first index.

In [2]:
print("Name:{1} (height {2} m, age {0})".format(64, "Bilbo", 0.84))

Name:Bilbo (height 0.84 m, age 64)


**List** can contain different types of objects, and are created using square brackets as in the following example:

In [3]:
x = [1, 'string', "another string"]   # Quote type is not important
x

[1, 'string', 'another string']

Elements in lists are indexed starting from 0, and are _mutable_ (can be changed):

In [4]:
x = [1, 2]
x[0] = 2       # Note that the first index is 0
x

[2, 2]

In contrast, **tuples** (with round brackets) are _immutable_ (cannot be changed). **Strings** are immutable as well. The following codes return an error message "'tuple' object does not support item assignment"

```Python
x = (1, 2)
x[0] = 2

**Lists** can be accessed via the _slice_ notation `[start:end]`. It is important to note that `end` is the index of the element that will not be selected, and that the first element has index 0.

In [5]:
a = [2, 3, 5, 7, 11, 13, 17, 19, 23]

In [6]:
a[1:4]    # Elements with index from 1 to 3

[3, 5, 7]

In [7]:
a[:4]     # All elements with index less than 4

[2, 3, 5, 7]

In [8]:
a[3:]     # All elements with index 3 or more

[7, 11, 13, 17, 19, 23]

In [9]:
a[-2:]    # The last two elements

[19, 23]

An _operator_ is a programming language construct that performs an action on one or more operands. The action of an operator in Python depends on the type of the operand(s). For example, operators such as +, *, -, and % that are arithmetic operators when th operands are of a numeric type, can have different meanings for objects of non-numeric type (such as strings).

In [10]:
'hello' + 'world'      # String concatenation

'helloworld'

In [11]:
'hello' * 2            # String repetition

'hellohello'

In [12]:
[1, 2] * 2             # List repetition

[1, 2, 1, 2]

In [13]:
15 % 4                 # Remainder of 15/4

3

## Pyton Objects

Each object has a list of _attributes_, and each attribute is a reference to another object. The function **dir** applied to an object and returns the list of attributes.

In [14]:
s = 'hello'
d = dir(s)
print(d, flush = True)     # Print he list in "flushed" format

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


Any attribute `attr` of an object `obj` can be accessed via the _dot notation_: `obj.attr`. To find more information about any object use the **help** function.

In [15]:
s = 'hello'
help(s.replace)

Help on built-in function replace:

replace(old, new, count=-1, /) method of builtins.str instance
    Return a copy with all occurrences of substring old replaced by new.
    
      count
        Maximum number of occurrences to replace.
        -1 (the default value) means replace all occurrences.
    
    If the optional argument count is given, only the first count occurrences are
    replaced.



This shows that the attribute **replace** is in fact a function. An attribute that is a function is called a _method_. We can use the **replace** method to create a new string from the old one by changing certain characters.

In [16]:
s = 'hello'
s1 = s.replace('e', 'a')
s1

'hallo'

## D.3 Types and Operators

Each object has a _type_. Three basic types in Python are `str` (for string), `int` (for integers), and `float` (for floating point numbers). The function **type** returns the type of an object.

In [17]:
t1 = type([1, 2, 3])
t2 = type((1, 2, 3))
t3 = type({1, 2, 3})
print(t1, t2, t3)

<class 'list'> <class 'tuple'> <class 'set'>


The _assignment_ operator, `=`, assigns an object to a variable; e.g., `x = 12`. An _expression_ is a combination of values, operators, and variables that yields another value or variable.

It is important to understand that a variable in Python is a _reference_ to an object - think of it as a label on a shoe box. Even though the label is a simple entity, the _contents_ of the shoe box (the object to which the variable refers) can be arbitrarily complex. Instead of moving the contents of one shoe box to another, it is much simpler to merely move the label.

In [18]:
x = [1, 2]
y = x                   # y refers to the same object as x
print(id(x) == id(y))   # check that the object id's are the same

True


In [19]:
print(x)
print(y)

[1, 2]
[1, 2]


In [20]:
y[0] = 100              # change the contents of the list that y refers to
print(x)
print(y)

[100, 2]
[100, 2]


Another example:

In [21]:
x = [1, 2]
y = x                   # y refers to the same object as x
y = [100, 2]            # now y refers to a different object
print(id(x) == id(y))

False


In [22]:
print(x)

[1, 2]


Several of the numerical operators can be combined with an assignment operator, as in `x += 1` to mean `x = x +1`. Operators shuch as + and * can be defined for other data types as well, where they take on a different meaning. This is called operator _overloading_, an example of which is the use of `<List> * <Integer>` for list repetition.

## D.4 Functions and Methods

Functions make it easier to divide a complex program into simpler parts. To create a _function_, use the following syntax:

```Python
def <function name>(<parameter_list>):
    <statements>
```

Note that the statements within a function must be indented. This is Python's way to define where a function begins and ends.

The following program highlights some of the subtleties of variables and objects in Python.

In [23]:
x = [1, 2, 3]

def change_list(y):
    y.append(100)       # Append an element to the list referenced by y
    y[0] = 0            # Modify the first element of the same list
    y = [2,3,4]         # The local y now refers to a different list
                        # The list to which y first referred does not change
    return sum(y)

In [24]:
print(change_list(x))

9


In [25]:
print(x)

[0, 2, 3, 100]


Variables that are defined inside a function only have _local scope_; that is, they are recognized only within that function. This allows the same variable name to be used in different functions without creating a conflict. If any variable is used within a function, Python first checks if the variable has local scope. If this is not the case (the variable has not been defined inside the function), then Python searches for that variable outside the function (the global scope). The following program illustrates several important points.

In [26]:
from numpy import array, square, sqrt

x = array([1.2, 2.3, 4.5])

def stat(x):
    n = len(x)               # the length of x
    meanx = sum(x)/n
    stdx = sqrt(sum(square(x - meanx))/n)
    return [meanx, stdx]

In [27]:
print(stat(x))

[2.6666666666666665, 1.3719410418171119]


1. Basic math functions such as **sqrt** are unknown to the standard Python interpreter and need to be imported.
2. Indentation is crucial. It shows where the function begins and ends.
3. No semicolons are needed to end lines, but the first line of the function definition (here line 5) must be end with a colon (:). Semicolons can be used to put multiple commands on a single line.
4. Lists are not arrays (vectors of numbers), and vector operations cannot be performed on lists. However, the **numpy** module is designed specifically with efficient vector/matrix operations in mind. On the second code line, we define `x` as a vector (ndarray) object. Functions such as **square**, **sum**, and **sqrt** are then applied to such arrays. Note that we used the default Python functons **len** and **sum**.
5. Running the program with `stat(x)` instead of `print(stat(x))` will not show any output in the console.

To display the complete list of built-in functions, type (using double underscoes)

```Python
dir(__builtin__)
```

```Python
dir(__builtin__)

## D.5 Modules

A Python _module_ is a programming construct that is useful for organizing code into manageable parts. To each module with name `module_name` is associated with a Python file `module_name.py` containing any number of definitions, e.g., of functions, classes, and variables, as well as executable statements. Modules can be imported into other programs using the syntax: `import <module_name> as <alias_name>`, where `<alias_name>` is a shorthand name for the module.

When imported into another Python file, the module name is treated as a _namespace_, providing a naming system where each object has its unique name. For example, different modules **mod1** and **mod2** can have different **sum** functions, but they can be distinguished by prefixing the function name with the module name via the dot notation, as in `mod1.sum` and `mod2.sum`. For example, the following code uses the **sqrt** function of the **numpy** module.

In [28]:
import numpy as np
np.sqrt(2)

1.4142135623730951

It is also possible to import only specific functions from a module using the syntax: `from <module_name> import <fnc1, fnc2, ...>`.

In [29]:
from numpy import sqrt, cos
print(sqrt(2))
print(cos(1))

1.4142135623730951
0.5403023058681398


##  Flow Control

The syntax for `if-then-else` flow control is as follows.

```Python
if <condition1>:
  <statements>
elif <condition2>:
  <statements>
else:
  <statements>

The `while` and `for` loops have the following syntax.
>
```Python
while <condition>:
  <statements>

for <variable> in <collection>:
  <statements>

Above, `<collection>` is an iterable object.

## Iteration

Iterating over a sequence of objects, such as used in a `for` loop, is a common operation. To better understand how iteration works, we consider the following code.

In [30]:
s = "Hello"
for c in s:
  print(c,'*', end=' ')

H * e * l * l * o * 

A string is an example of a Python object that can be iterated. One of the methods of a string object is `__iter__`. Any object that has such a method is called and _iterable_. Calling this method creates an _iterator_ - an object that returns the next element in the sequence to be iterated. This is done via the method `__next__`.

In [31]:
s = "Hello"
t = s.__iter__()           # t is now an iterator. Same as iter(s)
print(t.__next__())        # same as next(t)
print(t.__next__())
print(t.__next__())

H
e
l


The inbuilt functions **next** and **iter** simply call these corresponding double underscore functions of an object.

In [32]:
# Alternate method
s = "Hello"
k = iter(s)
print(next(k))
print(next(k))
print(next(k))

H
e
l


When executing a `for` loop, the sequence/collection over which to iterate must be an iterable. During the execution of the `for` loop, an iterator is created and the **next** function is executed until there is no next element. An iterator is also an iterable, so can be used in a `for` loop as well. Lists, tuples, and strings are so-called _sequence_ objects and are iterables, where the elements are iterated by their index.

The most common iterator in Python is the _range_ iterator, which allows iteration over a range of indices. Note that **range** returns a `range` object, not a list.

In [33]:
for i in range(4,20):
  print(i, end = ' ')
print(range(4,20))

4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 range(4, 20)


Two other common iterables are sets and dictionaries. Python _sets_ are, as in mathematics, unordered collections of unique objects. Sets are defined with curly brackets {}, as opposed to round brackets () for tuples, and square brackets [] for lists. Unlike lists, sets do not have duplicate elements. Many of the usual set operations are implemented in Python, including union `A | B` and intersection `A & B`.

In [34]:
A = {3, 2, 2, 4}
B = {4, 3, 1}
C = A & B
for i in A:
    print(i)
print(C)

2
3
4
{3, 4}


A useful way to construct lists is by _list comprehension_; that is, by expressions of the form

```Python
<expression> for <element> in <list> if <condition>

For sets a similar construction holds. In this way, lists and sets can be defined using very similar syntax as in mathematics.

In [35]:
setA = {3, 2, 4, 2}
setB = {x**2 for x in setA}
print(setB)

{16, 9, 4}


In [36]:
listA = [3, 2, 4, 2]
listB = [x**2 for x in listA]
print(listB)

[9, 4, 16, 4]


A _dictionary_ is a set-like data structure, containing one or more `key:value` pairs inclosed in curly brackets. The keys are often of the same thype, but do not have to be; the same holds for the values. Here is a simple example, storing the ages of Lord of the Rings characters in a dictionary.

In [37]:
DICT = {'Gimly': 140, 'Frodo': 51, 'Aragorn': 88}
for key in DICT:
    print(key, DICT[key])

Gimly 140
Frodo 51
Aragorn 88


## D.8 Classes

## D.9 Files

## D.10 NumPy

The package NumPy (module name **numpy**) provides the building blocks for scientific computing in Python. It contains all the standard mathematical functions, such as **sin**, **cos**, **tan**, etc., as well as efficient functions for random number generation, linear algebra, and statistical computation.

In [38]:
import numpy as np               # import the package
x = np.cos(1)
data = [1,2,3,4,5]
y = np.mean(data)
z = np.std(data)
print('cos(1) = {0:1.8f} mean = {1} std = {2}'.format(x, y, z))

cos(1) = 0.54030231 mean = 3.0 std = 1.4142135623730951


### D.10.1 Creating and Shaping Arrays

The fundamental data type in **numpy** is `ndarray`. This data type allow for fast matrix operations via highly optimized numerical libraries such as LAPACK and BLAS;, this in contrast to (nested) lists. As such, **numpy** is often essential when dealing with large amounts of quantitative data.

`ndarray` objects can be created in various ways. The following code creates a 2x3x2 array of zeros. Think of it as a 3-dimensional matrix or two stacked 3x2 matrices.

In [39]:
A = np.zeros([2,3,2])      # 2 by 3 by 2 array of zeros
print(A)
print(A.shape)             # number of rows and columns
print(type(A))             # A is an ndarray

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
(2, 3, 2)
<class 'numpy.ndarray'>


We will be mostly working with 2D arrays; that is, `ndarrays` that represent ordinary matrices. We can also use the **range** method and lists to create `ndarrays` via the **array** method. Note that **arange** is **numpy**'s version of **range**, with the difference that **arange** returns and `ndarray` object.

In [40]:
a = np.array(range(4))                # equivalent to np.arange(4)
A = np.arange(4)
b = np.array([0,1,2,3])
C = np.array([[1,2,3],[3,2,1]])
print(a, '\n', A, '\n', b,'\n' , C)

[0 1 2 3] 
 [0 1 2 3] 
 [0 1 2 3] 
 [[1 2 3]
 [3 2 1]]


The dimension of an `ndarray` can be obtained via its **shape** method, which returns a tuple. Arrays can be reshaped via the **reshape** method. This does not change the current `ndarray` object. To make the change permanent, a new instance needs to be created. 

In [41]:
a = np.array(range(9))          # a is an ndarray of shape (9,)
print(a.shape)

(9,)


In [42]:
A = a.reshape(3,3)              # A is an ndarray of shape (3,3)
print(a)

[0 1 2 3 4 5 6 7 8]


In [43]:
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


One shape dimension for **reshape** can be specified as -1. The dimension is then inferred from the other dimension(s).

In [44]:
b = np.array(range(8))
B1 = b.reshape(-1,4)
print(B1)

[[0 1 2 3]
 [4 5 6 7]]


In [45]:
B2 = b.reshape(4,-1)
print(B2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


The '`T`' attribute of an `ndarray` gives its transpose. Note that the transpose of a "vector" with shape (_n_, ) is the same vector. To distinguish between column and row vectors, reshape such a vector to an _n_ x 1 and 1 x _n_ array, respectively.

In [46]:
a = np.arange(3)               # 1D array (vector) of shape (3, )
print(a)
print(a.shape)

[0 1 2]
(3,)


In [47]:
b = a.reshape(-1,1)            # 3x1 array (matrix) of shape (3,1)
print(b)                       # a column vector
print(b.shape)                 

[[0]
 [1]
 [2]]
(3, 1)


In [48]:
print(b.T)                     # a row vector

[[0 1 2]]


Two useful methods of joining arrays are **hstack** and **vstack**, where the arrays are joind horizontally and vertically, respectively.

In [49]:
A = np.ones((3,3))
B = np.zeros((3,2))
C = np.hstack((A,B))
print(C)

[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


### D.10.2 Slicing

Arrays can be sliced similarly to Python lists. If an array has several dimensions, a slice for each dimension needs to be specified. Recall that Python indexing starts at '`0`' and ends at '`len(obj)-1`'. The following program illustrates various slicing operations.

In [50]:
A = np.array(range(9)).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
print(A[0])            # first row

[0 1 2]


In [52]:
print(A[:,1])          # second column

[1 4 7]


In [53]:
print(A[0,1])          # element in first row and second cloumn

1


In [54]:
print(A[0:1, 1:2])     # (1,1) ndarray containing A[0,1] = 1

[[1]]


In [55]:
print(A[1:,-1])        # elements in 2nd and 3rd rows, and last column

[5 8]


Note that ndarrays are mutable objects, so that elements can be modified directly, without having to create a new object.

In [56]:
A[1:,1] = [0,0]        # change two elements in the matrix A above
print(A)

[[0 1 2]
 [3 0 5]
 [6 0 8]]


### D.10.3 Array Operations

Basic mathematical operators and functions act element-wise on `ndarray` objects.

In [57]:
x = np.array([[2,4],[6,8]])
print(x)

[[2 4]
 [6 8]]


In [58]:
y = np.array([[1,1],[2,2]])
print(y)

[[1 1]
 [2 2]]


In [59]:
print(x+y)

[[ 3  5]
 [ 8 10]]


In [60]:
print(np.divide(x,y))       # same as x/y

[[2. 4.]
 [3. 4.]]


In [61]:
print(np.sqrt(x))

[[1.41421356 2.        ]
 [2.44948974 2.82842712]]


In order to compute matrix multiplications and compute inner products of vectors, **numpy**'s **dot** function can be used, either as a method of an `ndarray` instance or as a method of `np`.

In [62]:
print(np.dot(x,y))

[[10 10]
 [22 22]]


In [63]:
print(x.dot(y))

[[10 10]
 [22 22]]


In [64]:
print(x.dot(x))            # same as np.dot(x,x)

[[28 40]
 [60 88]]


In [65]:
print(np.dot(x,x))

[[28 40]
 [60 88]]


It is possible to multiply two `ndarrays` using the `@` _operator_ (which implements the **np.matmul** method). For matrices, this is similar to using the **dot** method. For higher-dimensional arrays the two methods behave differently.

In [71]:
print(x @ y)

[[10 10]
 [22 22]]


Recalled that the dimension of an `ndarray` can be obtained via its **shape** method, which retruns a tuple. Further, arrays can be reshaped via the **reshape** method.

In [72]:
a = np.array(range(12))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [78]:
print(a.shape)       # dimension of a

(12,)


In [79]:
A1 = a.reshape(2,-1)
print(A1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [80]:
print(A1.shape)      # dimension of A1

(2, 6)


In [76]:
A2 = a.reshape(3,-1)
print(A2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [81]:
print(A2.shape)      # dimension of A2

(3, 4)


$(m_1, m_2, ..., m_p)$

In [66]:
A = np.arange(4).reshape(2,2)
print(A)

[[0 1]
 [2 3]]


In [67]:
x1 = np.array([40,500])
print(x1)

[ 40 500]


In [68]:
x2 = x1.reshape(2,1)
print(x2)

[[ 40]
 [500]]


In [69]:
print(A + x1)         # shapes (2,2) and (2, )

[[ 40 501]
 [ 42 503]]


In [70]:
print(A * x2)

[[   0   40]
 [1000 1500]]
